name: Hello World Workflow

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Just Print Hello World 10 times
      run: |
        for i in {1..100}; do
          echo "$i Hello World..."
          sleep 10
        done
