name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Just Print Hello World 10 times
      run: |
        for i in {1..10}; do
          echo "Hello World"
        done
